
#+TITLE: Yet another Javascript compiler Macascript
#+AUTHOR: 浅井　政太郎 (Masataro Asai from Univ. of Tokyo)
#+LANGUAGE: ja
#+EMAIL: guicho2.71828@gmail.com
#+STYLE: <link rel="stylesheet" type="text/css" href="readme.css" />
#+INFOJS_OPT: view:info toc:t

* Yet another Javascript compiler Macascript

Macascript is a simple javascript compiler which is inspired
by parenscript and coffeescript.

I wasn't satisfied with either of them, so I made one myself.

Macascript supports :
+ Conditional statements which returns a value
+ Postfix if/unless
+ Iteration with automatically collecting results if necessary
+ Implicit return
+ Call/cc
+ Lisp Macro
+ etc...

Because macascript is aimed to be in fairly good accordance with Lisp
and Macro, extending its syntax is far more easier than the other
languages.  Some feature like &rest or &optional
(which are already suppoerted in coffeescript) are soon to be
implemented.

* Extend the syntax -- the algorythm of  macascript

The macascript source code is simple because it uses pattern
matching to parse the syntax tree.

DEFMACA macro expands the syntax tree. (currently all syntaxes are
implemented with DEFMACA.) The tree is compiled into 'compiled' special
operator, which tells the compiler that the particular expression need
not be compiled anymore. Finally, the compiled s-expression tree will
be passed to a function `maca-format', which flattens the tree and
prints its components. DEFMACA is almost identical to
defmacro, so the people who knows macro would feel it really
easy and fun to use.

* How to try
** recommended software
+ [[http://www.sbcl.org/][sbcl]] : The only lisp implimentation I've tested.
+ [[http://www.quicklisp.org/][quicklisp]] : great software.
+ [[http://common-lisp.net/project/slime/][slime]] : I greatly recommend you to install it if you are using
  emacs. I'm an emacs user and don't know well about vim, so if you
  have any information about a good interactive interface from vim to
  lisp please tell me about it.
+ packages : install them via quicklisp.
  + cl-match
  + alexandria
  + anaphora : I don't use it so much, but it's sometimes useful.
  + cl-ppcre

** run
Macascript is just an experimental code.
so open the REPL in the repository and input these code to the interpreter: 

+ if your implementation supports 'require:
  + (require 'macascript)
  + (in-package :maca)
  + (recompile)
+ or else:
  + (asdf:operate 'asdf:load-op 'macascript)
  + (in-package :maca)
  + (recompile)

* Examples
** Fundamentals

#+BEGIN_SRC lisp
(maca (-> (a)
          (if (a b c)                   ;multi-line then/else
              ((var d (+ a b c))        ;infix argument and var declaration
               (var e (== a b c d)))                  ; multiple comparison
              ((var f '(a (b c) (+ 1 2 3)))           ; array literal
               (var g (:a a :b (b c) :c (+ 1 2 3))))) ; object literal
          ;; true if it's not undefined
          (if? a b c)

          (granpa > parent > obj > (child 2) > grandchild 3 4 5)
          ;; direct access with []
          (obj > 2 > "key" > 'key > :key)
          ;; prototype accessor
          (obj >> child > grandchild)
          (obj >> (method a))
          (obj >>)
          ;; existantial accessor
          (a ? b ? c)

	  ;; if-statement with returning a value
	  ;; and alias from "or" to ||, "and" to &&
	  (or ((if a b c) > '(if d e f)) (and (x a) (x b)))
	  ;; implicit return
	  a))
#+END_SRC

#+BEGIN_SRC js
function(a){
	var d,e,f,g,tmp203,tmp204;
	if(a(b,c)){d = (a + (b + c))e = (a==b)&&(b==c)&&(c==d)
	}else{f = [a,b(c),(1 + (2 + 3))]g = {a:a,b:b(c),c:(1 + (2 + 3))
		}
	};
	if(((a!==undefined) && ((typeof a)!=="undefined"))){b
	}else{c
	};
	granpa.parent.obj.child(2).grandchild(3,4,5);
	obj[2]["key"][key][key];
	obj.prototype.child.grandchild;
	obj.prototype.method(a);
	obj.prototype;
	((((g1625 = a.b)!=undefined))?(((((g1626 = g1625.c)!=undefined))?(g1626):((void 0)))):((void 0)));
	(if(a){tmp203 = b
	}else{tmp203 = c
	}if(d){tmp204 = e
	}else{tmp204 = f
	}tmp203[tmp204] || (x(a) && x(b)));
	return a;
};
#+END_SRC

** Procedure/Inline/Inherit-this function

#+BEGIN_SRC lisp
(maca (-/> ()
          ;; inline function: maca expands it safely
          (-/ baz (a b) (+ (some-operation a) (other-operation b)))
          (= foo (baz foo bar))

          ;; procedure function: functions without a implicit return
          (-/> (b)
              (if (< b 3)
                  (var a (+ 3 b))
                  (var a (+ b 3)))
              (= @a 2)                  ; alias for this[a]
              ;; inherit-this function (=>): saves 'this' of the outer environment 
              (($ "button") > (click (=> (e) (alert (this > 2))))))))
#+END_SRC

#+BEGIN_SRC js
function(){
	var tmp1443,tmp1444,tmp24;
	;
	
	tmp1444 = bar;
	tmp1443 = foo;
	tmp24 = (someOperation(tmp1443) + otherOperation(tmp1444));foo = tmp24;
	function(b){
		var a,t1452,f1453;
		t1452 = this;
		f1453 = function(e){
			return alert(t1452[2]);
		};
		if((b<3)){a = (3 + b)
		}else{a = (b + 3)
		};
		this.a = 2;
		$("button").click(f1453);
	};
};
#+END_SRC
** Call/cc

#+BEGIN_SRC lisp
(maca ((alert
		(with-cc (cont)
		  ($ > (get "http://google.com"
					(-/> (xhr) (cont (xhr > responce-text)))))))))

(maca ((var cc1)
	   (var cc2)
	   (var cc3)
	   (console > log (with-cc (cont1) 
			  (= cc1 cont1)
			  (cont1 (confirm "one")))
			(with-cc (cont2)
			  (= cc2 cont2)
			  (cont2 (confirm "two")))
			5
			(with-cc (cont3)
			  (= cc3 cont3)
			  (cont3 (confirm "three")))
			4)
	   (cc1 "one-again") (// "this will call cont2 and cont3 again")
	   (cc1 "two-again") (// "this will call cont3 again")
	   (cc1 "three-again") (// "this will call alert")
	   ))
#+END_SRC

#+BEGIN_SRC js
var callLambda;
callLambda = function(fn){
	return fn.call(this);
};
Object.prototype.callLambda = callLambda;

callLambda(((function(cont){
	$.get("http://google.com",function(xhr){
		cont(xhr.responceText);
	});
})(function(valueArg951){
	var tmp121;
	return tmp121 = function(){
		var tmp121;
		return tmp121 = (this.alert || alert)(valueArg951);
	};
})));;

var cc1,cc2,cc3;

console.callLambda(((function(cont1){
	cc1 = cont1;
	cont1(confirm("one"));
})(((function(cont2){
	cc2 = cont2;
	cont2(confirm("two"));
})(((function(cont3){
	cc3 = cont3;
	cont3(confirm("three"));
})(function(valueArg966){
	return function(valueArg963){
		return function(valueArg960){
			var tmp121;
			return tmp121 = function(){
				var tmp121;
				return tmp121 = (this.log || log)(valueArg960,valueArg963,5,valueArg966,4);
			};
		};
	};
})))))));
cc1("one-again");
 /* this will call cont2 and cont3 again */
;
cc1("two-again");
 /* this will call cont3 again */
;
cc1("three-again");
 /* this will call alert */
;;
#+END_SRC

** other supported syntaxes

+ Try-Catch-Finally.
+ Iteration. It automatically collects the value of implicit return,
  but it won't do it when it's not needed.
+ while, do-while (which returns a value)
+ switch, with multiple cases

** Using defmaca to define a new syntax

Because macascript inherited the power of Macro from Common Lisp,
macascript has its own syntax ``defmaca'' which defines a new macascript
syntax.

#+BEGIN_SRC lisp
(defmaca my-if (condition then &optional else)
  `(if ,condition
       ,then
       ,else))

(maca (-> (a) (my-if a true false)))

#+END_SRC

If you really want to use the example above, you have to 
add the syntax pattern to the appropriate parameter. This will be
soon improved so that DEFMACA takes another argument for the
matching pattern and automatically add it to the list.

see test.maca for more examples.

* Motivation

The motivation is that Parenscript doesn't seem to fit the need of
javascript programmers. It is rather a utility for the lisp
programmers who dynamically produces javascript code on the server
side. Parenscript is still JUST LISP while Coffeescript is trying to
follow the rule "It's just JavaScript".  The syntax was more on the
Lisp side, like loop and let. (of course you can now use 'let' in the
javascript 1.8 or newer, but it is still not available on the platform
like Titanium Mobile, which I'm currently writing js programs for.)

Besides, it often produces invalid js code. (Note that I only mention about the
old version of parenscript because I haven't been watching the project
recently.) I wanted to fix that up, but the code! Parenscript's source
code was a mess for me. I gave up.

Another motivation still. As you know, coffeescript is so cool. 
It has the better, simple and beautiful syntax.
It improved almost all of the bad points in javascript.

However IT DOESN'T HAVE MACRO!!!!! 

On the smartphone product, runtime speed is highly required for the
user experience. And js is so slow compared with Obj-C or Java, the
standard language for smartphone development. Only the compile-time
macro can handle the optimization stuff like inline function, source
code simplification, etc.

Moreover, since coffeescript TRIES TO OMIT PARENTHESES, it must use
the parser. It makes the source code complicated and
PROCEDURAL. Procedual, so its not easy to extend.

* license

Currently I haven't decided which license I should choose. 
I suppose MIT license best suits the condition...

* Author

Masataro Asai (guicho2.71828@gmail.com)
Univ. of Tokyo

