
#+TITLE: Yet another Javascript compiler Macascript
#+AUTHOR: 浅井　政太郎 (Masataro Asai from Univ. of Tokyo)
#+LANGUAGE: ja
#+EMAIL: guicho2.71828@gmail.com
#+STYLE: <link rel="stylesheet" type="text/css" href="readme.css" />
#+INFOJS_OPT: view:info toc:t

* Yet another Javascript compiler Macascript

Macascript is a simple javascript compiler which is inspired
by parenscript and coffeescript.

I wasn't satisfied with either of them, so I made one myself.

Macascript supports :
+ Conditional statements which returns a value
+ Postfix if/unless
+ Iteration with automatically collecting results if necessary
+ Implicit return
+ Call/cc (not fully functional, it's valid only when it is in the
  middle of a function call. Use try/catch for /global exti/.)
+ Lisp Macro
+ etc...

Because macascript is aimed to be in fairly good accordance with Lisp
and Macro, extending its syntax is far more easier than the other
languages.  Some feature like &rest or &optional
(which are already suppoerted in coffeescript) are soon to be
implemented.

* Extend the syntax -- the algorythm of  macascript

The macascript source code is simple because it uses pattern
matching to parse the syntax tree.

DEFMACA macro expands the syntax tree. (currently all syntaxes are
implemented with DEFMACA.) The tree is compiled into 'compiled' special
operator, which tells the compiler that the particular expression need
not be compiled anymore. Finally, the compiled s-expression tree will
be passed to a function `maca-format', which flattens the tree and
prints its components. DEFMACA is almost identical to
defmacro, so the people who knows macro would feel it really
easy and fun to use.

* How to try
** recommended software
+ [[http://www.sbcl.org/][sbcl]] : The only lisp implimentation I've tested.
+ [[http://www.quicklisp.org/][quicklisp]] : great software.
+ [[http://common-lisp.net/project/slime/][slime]] : I greatly recommend you to install it if you are using
  emacs. I'm an emacs user and don't know well about vim, so if you
  have any information about a good interactive interface from vim to
  lisp please tell me about it.
+ packages : install them via quicklisp.
  + cl-match
  + alexandria
  + anaphora : I don't use it so much, but it's sometimes useful.
  + cl-ppcre

** run
Macascript is just an experimental code.
so open the REPL in the repository and input these code to the interpreter: 

+ if your implementation supports 'require:
  + (require 'macascript)
  + (in-package :maca)
  + (recompile)
+ or else:
  + (asdf:operate 'asdf:load-op 'macascript)
  + (in-package :maca)
  + (recompile)

* Examples
** Fundamentals

#+BEGIN_SRC lisp
(defun fundamentals ()
  ;; fundamentals
  (maca (glue a 2 space "string")
		(paren a)
		(paren (paren a))			;reduces redundancy automatically
		(paren (paren (paren a)))			;reduces redundancy automatically
		(comma (comma a b c) (comma a b c))
		(comma a b c)
		(stringify a)
		(blk ((a b c)))
		(blk 
		 ((blk 
		   ((a b c)))))
		(bracket a)
		;; constants and basic assignments
		undefined
		t
		"string"
		;; comments (if you want to include some comment into js)
		(// "haaa~~~~ this is comfortable")
		(// a)))
#+END_SRC

#+BEGIN_SRC js
MACA> (fundamentals)

a2 "string";
(a);
((a));
(((a)));
a,b,c,a,b,c;
a,b,c;
'a';
{ /* indentation level: 0 */
	a(b,c);
}
;
{ /* indentation level: 0 */
	{ /* indentation level: 1 */
		a(b,c);
	}
	;
}
;
[a];
undefined;
true;
"string";
 /* haaa~~~~ this is comfortable */;
 /* A */;
#+END_SRC


** Assignments

#+BEGIN_SRC lisp
(defun assignments ()
  ;; assignments
  (maca (= number 3)
		(blk ((= number 3) (= number 3)))
		(with-label (label) 
		  (= number 3)
		  (= number 3))
		(comma (= number 3) (= number 3)))
  (maca	(var number 3))
  (maca (var number))
  ;;(maca (var (+ 2 1) 3)) ;throws error
  )
#+END_SRC

#+BEGIN_SRC js
MACA> (assignments)

number = 3;
{ /* indentation level: 0 */
	number = 3;
	number = 3;
}
;
label:{ /* indentation level: 0 */
	number = 3;
	number = 3;
}
;
number = 3,number = 3;

var number;
number = 3;

var number;
#+END_SRC

** Operaters

#+BEGIN_SRC lisp
(defun ops ()
  ;; infix
  (maca (>>> number 3)
		(+ a 3)
		(+ a 3 4)
		(- a 3 4)
		(* a 3 4)
		(+ a 3 (>>> number 3))

		;; assignments
		(= a 3)
		(= a (a > b > v))
		(a > b > v)

		;; comparison
		(< number 50)
		(== 5 3)
		(== 5 3 4)
		(>= 5 3 4)

		;; mono-ops
		(new -number)
		(typeof 5)

		;; in
		(in 5 array)))
#+END_SRC

#+BEGIN_SRC js
MACA> (ops)

(number >>> 3);
(a + 3);
(a + (3 + 4));
(a NIL (3 NIL 4));
(a * (3 * 4));
(a + (3 + (number >>> 3)));
a = 3;
a = a.b.v;
a.b.v;
(number<50);
(5==3);
(5==3)&&(3==4);
(5>=3)&&(3>=4);
(new Number);
(typeof 5);
(5 in array);
#+END_SRC


** Procedure/Inline/Inherit-this function

#+BEGIN_SRC lisp
(defun functions ()
  ;; global scope(bare)
  (maca (a b c)
		(= d (- a b c))
		(var e 2)
		(+ a b c d e))

  ;; function definition
  ;; normal function: implicit return on
  ;; procedure function: returns undefined
  (maca (-/> (a)
			 (alert a)
			 (-> (b)
				 (if (< b 3)
					 ((var a (- 3 b))
					  (= b (expr a 5)))
					 ((var a (- b 3))))
				 (var c (+ a 3))
				 (alert a b)
				 a)))

  ;; inherit-this function: saves 'this' of the outer environment
  (maca (a > (click (=/> (e) 
						 (alert (this > 2))))))

  ;; inline function: they are directly expanded into the environment

  (maca (foo)
		(bar foo)
		(-/ baz (a b) (+ (some-operation a)
						 (other-operation b)))
		(-/ bud (a b) (+ (sqrt a)
						 (expr b)))

		(= foo (baz foo bar))
		(alert (baz 1 (bud foo bar)))))
#+END_SRC

#+BEGIN_SRC js
MACA> (functions)

var e;
a(b,c);
d = (a NIL (b NIL c));
e = 2;
(a + (b + (c + (d + e))));

var a,c;
function(a){ /* indentation level: 0 */
	var a,c;
	alert(a);
	function(b){ /* indentation level: 1 */
		var a,c;
		if((b<3)){ /* indentation level: 2 */
			a = (3 NIL b);
			b = expr(a,5);
		}
		else{ /* indentation level: 2 */
			a = (b NIL 3);
		}
		c = (a + 3)alert(a,b);
		return a;
	}
	;
}
;

var this3226,inheritedFn3227;
this3226 = this;
inheritedFn3227 = function(e){ /* indentation level: 0 */
	alert(this3226[2]);
}
;
a.click(inheritedFn3263);

var inlineTmp3266,inlineTmp3267,setterTemp3265,inlineTmp3283,inlineTmp3284,inlineTmp3286,inlineTmp3287,setterTemp3285,inlineTmp3303,inlineTmp3304,setterTemp3302,argName3282;
foo();
bar(foo);

inlineTmp3352 = bar;
inlineTmp3351 = foo;
setterTemp3350 = (someOperation(inlineTmp3351) + otherOperation(inlineTmp3352));
foo = setterTemp3350;


inlineTmp3438 = bar;
inlineTmp3437 = foo;
setterTemp3436 = (sqrt(inlineTmp3437) + expr(inlineTmp3438));
inlineTmp3418 = setterTemp3436;
inlineTmp3417 = 1;
argName3416 = (someOperation(inlineTmp3417) + otherOperation(inlineTmp3418));
alert(argName3416);
#+END_SRC
** Call/cc

#+BEGIN_SRC lisp
(defun continuation ()
  (maca (alert
		 (with-cc (cont)
		   ($ > (get "http://google.com"
					 (-/> (xhr) (cont (xhr > responce-text)))))))

		(var cc1)
		(var cc2)
		(alert (with-cc (cont1) 
				 (= cc1 cont1)
				 (cont1 (confirm "one")))
			   2
			   (with-cc (cont2)
				 (= cc2 cont2)
				 (cont2 (confirm "two"))))
		(console > (log (cc1 > (to-string))))
		(cc1 "one-again") (// "this will call cont2 again")

		(console > (log (cc2 > (to-string))))
		(cc2 "two-again")

		(// "if you want to use continuation for a method, do like this:")
		(funcall (console > log)
				 (with-cc (cont1) 
				   (= cc1 cont1)
				   (cont1 (confirm "one")))
				 (with-cc (cont2)
				   (= cc2 cont2)
				   (cont2 (confirm "two")))))

  ;; now you can use continuation with the infix operators.
  (maca (var cc)
	    (alert (+ 1 (with-cc (cont)
					  (= cc cont)
					  (cont 2))
				  3))
		(alert (cc 5))))
#+END_SRC

#+BEGIN_SRC js
var cc1,cc2;
(function(cont){ /* indentation level: 0 */
	return $.get("http://google.com",function(xhr){ /* indentation level: 1 */
		cont(xhr.responceText);
	}
	);
}
)(function(valueArg2207){ /* indentation level: 0 */
	return alert(valueArg2207);
}
);
(function(cont2){ /* indentation level: 0 */
	cc2 = cont2;
	return cont2(confirm("two"));
}
)(function(valueArg2318){ /* indentation level: 0 */
	return (function(cont1){ /* indentation level: 0 */
	cc1 = cont1;
	return cont1(confirm("one"));
}
)(function(valueArg2331){ /* indentation level: 1 */
		return alert(valueArg2318,2,valueArg2331);
	}
	);
}
);
console.log(cc1.toString());
cc1("one-again");
 /* this will call cont2 again */;
console.log(cc2.toString());
cc2("two-again");
 /* if you want to use continuation for a method, do like this: */;
(function(cont2){ /* indentation level: 0 */
	cc2 = cont2;
	return cont2(confirm("two"));
}
)(function(valueArg2448){ /* indentation level: 0 */
	return (function(cont1){ /* indentation level: 0 */
	cc1 = cont1;
	return cont1(confirm("one"));
}
)(function(valueArg2461){ /* indentation level: 1 */
		return console.log(valueArg2448,valueArg2461);
	}
	);
}
);

var cc;
alert((function(cont){ /* indentation level: 0 */
	cc = cont;
	return cont(2);
}
)(function(valueArg2554){ /* indentation level: 0 */
	return (1 + (valueArg2554 + 3));
}
));
alert(cc(5));
#+END_SRC

** other supported syntaxes

+ Try-Catch-Finally.
+ Iteration. It automatically collects the value of implicit return,
  but it won't do it when it's not needed.
+ while, do-while (which returns a value)
+ switch, with multiple cases

** Using defmaca to define a new syntax

Because macascript inherited the power of Macro from Common Lisp,
macascript has its own syntax ``defmaca'' which defines a new macascript
syntax.

#+BEGIN_SRC lisp
(defmaca my-if (condition then &optional else)
  `(if ,condition
       ,then
       ,else))

(maca (-> (a) (my-if a true false)))

#+END_SRC

If you really want to use the example above, you have to 
add the syntax pattern to the appropriate parameter. This will be
soon improved so that DEFMACA takes another argument for the
matching pattern and automatically add it to the list.

see test.maca for more examples.

* Motivation

The motivation is that Parenscript doesn't seem to fit the need of
javascript programmers. It is rather a utility for the lisp
programmers who dynamically produces javascript code on the server
side. Parenscript is still JUST LISP while Coffeescript is trying to
follow the rule "It's just JavaScript".  The syntax was more on the
Lisp side, like loop and let. (of course you can now use 'let' in the
javascript 1.8 or newer, but it is still not available on the platform
like Titanium Mobile, which I'm currently writing js programs for.)

Besides, it often produces invalid js code. (Note that I only mention about the
old version of parenscript because I haven't been watching the project
recently.) I wanted to fix that up, but the code! Parenscript's source
code was a mess for me. I gave up.

Another motivation still. As you know, coffeescript is so cool. 
It has the better, simple and beautiful syntax.
It improved almost all of the bad points in javascript.

However IT DOESN'T HAVE MACRO!!!!! 

On the smartphone product, runtime speed is highly required for the
user experience. And js is so slow compared with Obj-C or Java, the
standard language for smartphone development. Only the compile-time
macro can handle the optimization stuff like inline function, source
code simplification, etc.

Moreover, since coffeescript TRIES TO OMIT PARENTHESES, it must use
the parser. It makes the source code complicated and
PROCEDURAL. Procedual, so its not easy to extend.

* license

Currently I haven't decided which license I should choose. 
I suppose MIT license best suits the condition...

* Author

Masataro Asai (guicho2.71828@gmail.com)
Univ. of Tokyo

